

#server:
 # port: 8081
#  error:
#    whitelabel:
#      enabled: false

spring:
  #datasource:
   # url: jdbc:mysql://localhost:3306/myblog #change this to your database url
    #password: Macropay21 #change this to your database password 
    #username: GABRIEL #change this to your database username
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
  profiles:
    active:
    - prod
    
 # Spring security
logging:
  level:
    '[org.springframework.security]': DEBUG

## App properties
app:
  jwt-secret = JWTSecretKEy
  jwt-expiration-milliseconds = 604800000  