

#server:
 # port: 8081
#  error:
#    whitelabel:
#      enabled: false
server:
  port: 8081
#  error:
#    whitelabel:
#      enabled: false

spring:
  datasource:
    url: jdbc:sqlserver://187.188.105.90:1477;databaseName=testDB #change this to your database url
    password: Ago0102!* #change this to your database password 
    username: UserLuisF #change this to your database username
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
    
 # Spring security
logging:
  level:
    '[org.springframework.security]': DEBUG

## App properties
app:
  jwt-secret = JWTSecretKEy
  jwt-expiration-milliseconds = 604800000  